apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-connect-deployment
  labels:
    app: kafka-connect
spec:
  selector:
    matchLabels:
      app: kafka-connect
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
      - name: kafka-connect
        image: <registry-name>/kafka-mongo-connect:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083