apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  initContainers:
    - image: alpine/git
      name: git
      command:
        - git
        - clone
        - 'https://OmkarV23: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@github.com/OmkarV23/XAI.git'
        - /tmp/workspace
      volumeMounts:
        - name: app-data
          mountPath: /tmp/workspace
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.8.1
      args:
        - '--context=dir:///tmp/workspace/deployment/kubernetes/kafka-connect'
        - '--dockerfile=/tmp/workspace/deployment/kubernetes/kafka-connect/Dockerfile'
        - '--destination=<registry-name>/kafka-mongo-connect:latest'
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
        - name: app-data
          mountPath: /tmp/workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: dockercred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: app-data
      emptyDir: {}