apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "zookeeper.fullname" . }}-pdb
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  {{- include "zookeeper.minAvailable" . | nindent 2 }}
  selector:
    matchLabels:
      {{- include "zookeeper.selectorLabels" . | nindent 6 }}