---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-persistent-storage
spec:
  storageClassName: mongodb-data
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
            - key: type
              operator: In
              values:
                - cloud
            - key: provider
              operator: In
              values:
                - aws
            - key: service
              operator: In
              values:
                - ec2
            - key: region
              operator: In
              values:
                - us-west-1
            - key: availability_zone
              operator: In
              values:
                - us-west-1a