---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "mongo-db"
spec:
  serviceName: "mongo-db"
  replicas: 1
  selector:
    matchLabels:
      app: "mongo-db"
  template:
    metadata:
      labels:
        app: "mongo-db"
    spec:
      containers:
        - name: "mongo-db"
          image: "mongo"
          imagePullPolicy: "Always"
          env:
            - name: "MONGO_INITDB_ROOT_USERNAME"
              value: "admin"
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              value: "admin123"

          ports:
            - name: "mongo-external"
              containerPort: 27017
          volumeMounts:
            - name: "mongodb-persistent-storage"
              mountPath: "/data/db"
      volumes:
        - name: "mongodb-persistent-storage"
          persistentVolumeClaim:
            claimName: "mongodb-pvc"