apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - protocol: TCP
      name: kafka-producer
      port: 9092
      nodePort: 30092
      targetPort: 9092
    - protocol: TCP
      name: kafka-consumer
      port: 29092
      nodePort: 31092
      targetPort: 29092

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  serviceName: kafka-service
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: broker
          image: confluentinc/confluent-local:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
            - name: KAFKA_ADVERTISED_LISTENERS
              value: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: 'broker,controller'
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: '1@broker:29093'
            - name: KAFKA_LISTENERS
              value: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: 'PLAINTEXT'
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: 'CONTROLLER'
            - name: KAFKA_LOG_DIRS
              value: '/tmp/kraft-combined-logs'
            - name: KAFKA_REST_HOST_NAME
              value: rest-proxy
            - name: KAFKA_REST_BOOTSTRAP_SERVERS
              value: 'broker:29092'
            - name: KAFKA_REST_LISTENERS
              value: "http://0.0.0.0:8082"
            - name: CLUSTER_ID
              value: '4L6g3nShT-eMCtK--X86sw'
---

#apiVersion: apps/v1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: kafka-broker-autoscaler
##  namespace: kafka-cluster
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: StatefulSet
#    name: kafka-broker
#  minReplicas: 3
#  maxReplicas: 5
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: Utilization
#          averageUtilization: 70
