apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-watcher
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-watcher-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-watcher-cleaner-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-watcher-role
subjects:
  - kind: ServiceAccount
    name: pod-watcher
    namespace: default

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-cleanup
  namespace: default
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pod-watcher
          containers:
            - name: kubectl-container
              image: bitnami/kubectl:latest
              command: ["sh", "-c", "kubectl delete pod --field-selector=status.phase==Succeeded"]
          restartPolicy: Never
