---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-broker-data-1
spec:
  storageClassName: kafka-broker-data
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/kafka/data/broker/1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
            - key: type
              operator: In
              values:
                - cloud
            - key: provider
              operator: In
              values:
                - aws
            - key: service
              operator: In
              values:
                - ec2
            - key: region
              operator: In
              values:
                - us-west-1
            - key: availability_zone
              operator: In
              values:
                - us-west-1a
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-broker-data-2
spec:
  storageClassName: kafka-broker-data
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/kafka/data/broker/2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
            - key: type
              operator: In
              values:
                - cloud
            - key: provider
              operator: In
              values:
                - aws
            - key: service
              operator: In
              values:
                - ec2
            - key: region
              operator: In
              values:
                - us-west-1
            - key: availability_zone
              operator: In
              values:
                - us-west-1a
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-broker-data-3
spec:
  storageClassName: kafka-broker-data
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/kafka/data/broker/3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
            - key: type
              operator: In
              values:
                - cloud
            - key: provider
              operator: In
              values:
                - aws
            - key: service
              operator: In
              values:
                - ec2
            - key: region
              operator: In
              values:
                - us-west-1
            - key: availability_zone
              operator: In
              values:
                - us-west-1a