apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data-1
spec:
  storageClassName: zookeeper-data
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/kafka/data/zookeeper/1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
            - key: type
              operator: In
              values:
                - cloud
            - key: provider
              operator: In
              values:
                - aws
            - key: service
              operator: In
              values:
                - ec2
            - key: region
              operator: In
              values:
                - us-west-1
            - key: availability_zone
              operator: In
              values:
                - us-west-1a
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data-2
spec:
  storageClassName: zookeeper-data
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/kafka/data/zookeeper/2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
            - key: type
              operator: In
              values:
                - cloud
            - key: provider
              operator: In
              values:
                - aws
            - key: service
              operator: In
              values:
                - ec2
            - key: region
              operator: In
              values:
                - us-west-1
            - key: availability_zone
              operator: In
              values:
                - us-west-1a
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data-3
spec:
  storageClassName: zookeeper-data
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/kafka/data/zookeeper/3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
            - key: type
              operator: In
              values:
                - cloud
            - key: provider
              operator: In
              values:
                - aws
            - key: service
              operator: In
              values:
                - ec2
            - key: region
              operator: In
              values:
                - us-west-1
            - key: availability_zone
              operator: In
              values:
                - us-west-1a

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-log-data-1
spec:
  storageClassName: zookeeper-log-data
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/kafka/data/zookeeper_log/1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
            - key: type
              operator: In
              values:
                - cloud
            - key: provider
              operator: In
              values:
                - aws
            - key: service
              operator: In
              values:
                - ec2
            - key: region
              operator: In
              values:
                - us-west-1
            - key: availability_zone
              operator: In
              values:
                - us-west-1a
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-log-data-2
spec:
  storageClassName: zookeeper-log-data
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/kafka/data/zookeeper_log/2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
            - key: type
              operator: In
              values:
                - cloud
            - key: provider
              operator: In
              values:
                - aws
            - key: service
              operator: In
              values:
                - ec2
            - key: region
              operator: In
              values:
                - us-west-1
            - key: availability_zone
              operator: In
              values:
                - us-west-1a
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-log-data-3
spec:
  storageClassName: zookeeper-log-data
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/kafka/data/zookeeper_log/3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
            - key: type
              operator: In
              values:
                - cloud
            - key: provider
              operator: In
              values:
                - aws
            - key: service
              operator: In
              values:
                - ec2
            - key: region
              operator: In
              values:
                - us-west-1
            - key: availability_zone
              operator: In
              values:
                - us-west-1a
---